site_name: Team 5901 - Cougar Pack
nav:
    - Home: index.md
    - FRC Programming Outline: design.md
    - Updating Hardware: update.md    
    - Java Programming Basics: basics.md
    - Programming Commmands: commands.md
    - Programming Subsystems: subsystems.md
    - Programming the Controller: controllers.md
    - Vision: vision.md  
    - Pneumatics: pneumatics.md     
    - About: about.md

theme: readthedocs