site_name: Team 5901 - Cougar Pack
nav:
    - Home: index.md
    - FRC Programming Outline: design.md
    - FRC Java Basics: java.md
        
    - Basic Robot Code:
        - Programming Conventions: Basic - Conventions.md
        - Code Structure: Basic - Code Structure.md
        - Programming Subsystems: Basic - Subsystems.md
        - Programming Commmands: Basic - Commands.md
        - Programming the Controller: Basic - Controllers.md
    - Specialized Robot Code:      
        - Motor Controllers: Special - Motors.md
        - Sensors: Special - Sensors.md    
        - Camera: Special - Camera.md    
        - Vision: Special - Vision.md  
        - Pneumatics: Special - Pneumatics.md     
        - Autonomous (In Progress): autonomous.md         
    - Updating Hardware: update.md  
    - To Dos: ToDo.md
    - About: about.md

theme: 'readthedocs'